image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  dir: "aspnet-core/"

before_script:
  - "export ASPNETCORE_Environment=Development"
  - "cd aspnet-core/build"

build:
  stage: build
  script:
    - "./build-with-ng.ps1"