image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  dir: "aspnet-core/"

before_script:
  - "export ASPNETCORE_Environment=Development"
  - "cd EduVault"
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

build:
  stage: build
  script:
    - "dotnet publish"