image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  dir: "/home/devinnorm/EduVault/publish/"

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"