image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  dir: "~/aspnet-core/"

before_script:
  - "export ASPNETCORE_Environment=Development"
  - "ls"
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"