image: microsoft/dotnet:latest

stages:
  - build
  - deploy

variables:
  dir: "aspnet-core/"

before_script:
  - "export ASPNETCORE_Environment=Development"
  - "cd EduVault"
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

build:
  stage: build
  script:
    - "dotnet publish"

deploy:
  stage: deploy 
  script:
    - "ssh -i ~/.ssh/id_rsa.pub nataizya_s@104.154.235.209"
    - "ls"