image: microsoft/dotnet:latest

stages:
  - build
  - deploy

variables:
  dir: "aspnet-core/"

before_script:
  - "export ASPNETCORE_Environment=Development"
  - "cd EduVault"
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - "eval $(ssh-agent -s)"
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

#build:
 # stage: build
  #script:
   # - "echo 'doing build'"

deploy:
  stage: deploy 
  script:
    - "ssh nataizya_s@104.154.235.209"
    - "ls -la"